import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Check,Gamepad2,Keyboard,RotateCcw,X} from 'lucide-react';
import './controls.css';

const keyboardActions=[['Move Forward','Look Up','BOTH'],['Move Backward','Look Down','BOTH'],['Move Left','Look Left','BOTH'],['Move Right','Look Right','BOTH'],['Mouse Look Toggle','Toggle Mouse Look','APPLICATION'],['Recenter','Reset / Recenter','BOTH'],['Release / Exit','Close / Back','APPLICATION']];
const controllerActions=[['VR Trigger','A','APPLICATION'],['VR Grip','RB','APPLICATION'],['VR Menu','VIEW','APPLICATION'],['VR Trackpad Click','RIGHT STICK CLICK','APPLICATION'],['Mic Toggle','LEFT STICK CLICK','APPLICATION'],['Arm Up','D-PAD UP','THIRD PERSON'],['Arm Down','D-PAD DOWN','THIRD PERSON'],['Arm Left','D-PAD LEFT','THIRD PERSON'],['Arm Right','D-PAD RIGHT','THIRD PERSON']];
const keyNames={37:'Left Arrow',38:'Up Arrow',39:'Right Arrow',40:'Down Arrow',27:'Escape',119:'F8',82:'R'};
const gamepadNames={0:'A',1:'B',2:'X',3:'Y',4:'LT',5:'RB',6:'LEFT STICK CLICK',7:'RIGHT STICK CLICK',8:'VIEW',9:'MENU',64:'D-PAD UP',128:'D-PAD DOWN',256:'D-PAD LEFT',512:'D-PAD RIGHT'};
const controllerInputs=[0,1,2,3,4,5,6,7,8,9,64,128,256,512];
const call=async(name,args,fallbackValue)=>{try{return await invoke(name,args)}catch(error){return fallbackValue}};
const keyLabel=code=>keyNames[code]||String.fromCharCode(code);
const padLabel=code=>gamepadNames[code]||'UNASSIGNED';
const cloneBindings=b=>({bindings:Object.fromEntries(Object.entries(b?.bindings||{}).map(([name,value])=>[name,{...value}]))});

function BindingEditor({bindings,setBindings,device,actions,listening,setListening,onSaved}){
  const [conflict,setConflict]=useState(null);const [controllerState,setControllerState]=useState(null);const baseline=useRef(null);
  const valueFor=name=>bindings.bindings?.[name]||{device,code:0};
  const display=value=>value.device==='None'?'UNASSIGNED':value.device==='Keyboard'?keyLabel(value.code):padLabel(value.code);
  const candidateConflicts=(name,value)=>Object.entries(bindings.bindings||{}).filter(([other,current])=>other!==name&&current.device===value.device&&current.code===value.code&&value.device!=='None').map(([other])=>other);
  const stage=(name,value)=>{const others=candidateConflicts(name,value);if(others.length){setConflict({name,value,others});return;}setBindings(b=>({...b,bindings:{...b.bindings,[name]:value}}));setListening(null)};
  const startListening=name=>{setConflict(null);if(device==='Gamepad')baseline.current=controllerState||{buttons:0,dpad:8};setListening({name,device})};
  const onKeyDown=e=>{if(device==='Keyboard'&&listening){e.preventDefault();stage(listening.name,{device:'Keyboard',code:e.keyCode||e.which})}};
  useEffect(()=>{window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)});
  useEffect(()=>{if(device!=='Gamepad'||!listening)return;let alive=true;const timer=setInterval(async()=>{const next=await call('get_controller_status',{},null);if(!alive||!next)return;setControllerState(next);const before=baseline.current||next;const changed=controllerInputs.find(code=>code<32?((next.buttons&(1<<code))&&!((before.buttons||0)&(1<<code))):((next.dpad&code)&&!((before.dpad||0)&code)));if(changed!==undefined)stage(listening.name,{device:'Gamepad',code:changed});baseline.current=next},100);return()=>{alive=false;clearInterval(timer)}},[device,listening]);
  useEffect(()=>{if(device==='Gamepad')call('get_controller_status',{},null).then(setControllerState)},[device]);
  const resolveConflict=mode=>{if(!conflict)return;const next=cloneBindings(bindings);const other=conflict.others[0];next.bindings[other]=mode==='swap'?valueFor(conflict.name):{device:'None',code:0};next.bindings[conflict.name]=conflict.value;setBindings(next);setConflict(null);setListening(null)};
  const apply=async()=>{const saved=await call('save_bindings',{bindings},null);if(saved){setBindings(saved);onSaved('Bindings saved. Restart NOVR Bridge to apply native input changes.')}};
  const restore=()=>{if(window.confirm('Restore all Bigscreen NOVR controls to their default bindings?'))call('get_bindings',{},null).then(saved=>{if(saved){setBindings(saved);onSaved('Defaults restored.')}})};
  return <div className="binding-editor">{device==='Gamepad'&&<div className={`controller-live ${controllerState?.connected?'connected':''}`}><span>{controllerState?.connected?'●':'○'}</span>{controllerState?.connected?'XBOX CONTROLLER CONNECTED':'CONTROLLER NOT DETECTED'}</div>}<div className="binding-list">{actions.map(([name,label,mode])=>{const value=valueFor(name);return <div className="binding-row" key={name}><div><strong>{label}</strong><small>{mode}</small></div><span className="binding-value">{display(value)}</span><button onClick={()=>startListening(name)}>{listening?.name===name?'LISTENING…':'CHANGE'}</button></div>})}</div><div className="controls-actions"><button className="secondary-control" onClick={restore}><RotateCcw size={16}/> RESTORE DEFAULTS</button><button className="primary-control" onClick={apply}><Check size={16}/> APPLY</button></div>{listening&&<div className="listening-banner">LISTENING FOR {device==='Keyboard'?'KEYBOARD INPUT':'CONTROLLER INPUT'}… {device==='Keyboard'?'Press any key':'Press a controller button'} <button onClick={()=>setListening(null)}>CANCEL</button></div>}{conflict&&<div className="conflict-modal"><div className="conflict-card"><h3>BINDING CONFLICT</h3><p>{display(conflict.value)} is currently assigned to <b>{conflict.others[0]}</b>.</p><div><button onClick={()=>resolveConflict('swap')}>SWAP</button><button onClick={()=>resolveConflict('replace')}>REPLACE</button><button onClick={()=>setConflict(null)}>CANCEL</button></div></div></div>}</div>;
}

export default function Controls({onClose}){
  const [tab,setTab]=useState('keyboard');const [bindings,setBindings]=useState({bindings:{}});const [listening,setListening]=useState(null);const [notice,setNotice]=useState('');
  useEffect(()=>{call('get_bindings',{},null).then(value=>value&&setBindings(value))},[]);
  return <div className="controls-screen"><div className="controls-head"><div><p className="eyebrow">BIGSCREEN NOVR</p><h2>CONTROLS</h2><span>Input bindings from the working native runtime</span></div><button className="close-controls" onClick={onClose}><X size={20}/></button></div><div className="controls-tabs"><button className={tab==='keyboard'?'active':''} onClick={()=>{setTab('keyboard');setListening(null)}}><Keyboard size={18}/> KEYBOARD</button><button className={tab==='controller'?'active':''} onClick={()=>{setTab('controller');setListening(null)}}><Gamepad2 size={18}/> CONTROLLER</button></div><div className="controls-body">{tab==='controller'?<><div className="controller-visual"><div className="controller-glow"><Gamepad2 size={176}/></div><span className="callout lt">VR TRIGGER · A</span><span className="callout rt">VR GRIP · RB</span><span className="callout lb">VR MENU · VIEW</span><span className="callout rb">TRACKPAD · RIGHT STICK</span><span className="callout dpad">ARM ADJUST · D-PAD</span></div><div className="controls-list"><h3>SUPPORTED CONTROLLER INPUT</h3><p className="controls-note">These are the bindings the Bridge and VR driver actually consume. Camera axes remain fixed native controls.</p><BindingEditor bindings={bindings} setBindings={setBindings} device="Gamepad" actions={controllerActions} listening={listening} setListening={setListening} onSaved={setNotice}/></div></>:<div className="controls-list full"><h3>KEYBOARD HOTKEYS</h3><p className="controls-note">Defaults are read from the shared native binding configuration. Changes apply when the NOVR Bridge restarts.</p><BindingEditor bindings={bindings} setBindings={setBindings} device="Keyboard" actions={keyboardActions} listening={listening} setListening={setListening} onSaved={setNotice}/></div>}</div>{notice&&<div className="controls-notice">{notice}</div>}</div>;
}
